services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "My!Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pictures-api
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=PicturesDb;User Id=sa;Password=My!Pass123;TrustServerCertificate=True
    ports:
      - "5000:8080"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5171:80"
    depends_on:
      - api

volumes:
  sql_data:
